services:

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5437:5432'
    networks:
      - transcendence

  django:
    image: django
    container_name: django
    build:
      context: .
      dockerfile: requirements/django/Dockerfile
    volumes:
      - ./srcs:/app/srcs
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  transcendence:
    name: transcendence
