# Generated by Django 4.2.3 on 2024-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_matchchoice_remove_match_mm_remove_match_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='mm',
            field=models.CharField(choices=[('classé', 'Classé'), ('non classé', 'Non Classé'), ('tournoi', 'Tournoi')], default='non classé', max_length=20),
        ),
    ]
