# Generated by Django 4.2.3 on 2024-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_alter_matchchoice_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='matchmaker.History', to='matchmaker.player'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('match', 'player')},
        ),
    ]
