# Generated by Django 4.2.3 on 2024-09-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0006_alter_history_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together={('connect', 'mode', 'mm')},
        ),
    ]
