# Generated by Django 4.2.3 on 2024-09-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersession',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='playersession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regulargamesession',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='regulargamesession',
            name='players',
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='PlayerSession',
        ),
        migrations.DeleteModel(
            name='RegularGameSession',
        ),
    ]
