# Generated by Django 4.2.3 on 2024-09-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('velocity_x', models.FloatField(default=1)),
                ('velocity_y', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('coordinates', models.FloatField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='RegularGameSession',
            fields=[
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_session', serialize=False, to='api.ball')),
                ('players', models.ManyToManyField(through='api.PlayerSession', to='account.user')),
            ],
        ),
        migrations.AddField(
            model_name='playersession',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_sessions', to='api.regulargamesession'),
        ),
    ]
