# Generated by Django 5.0.6 on 2024-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.FloatField()),
                ('friends', models.IntegerField()),
                ('online', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PongPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('gamesWon', models.FloatField()),
                ('gamesTotal', models.FloatField()),
                ('gamesWonMulti', models.FloatField()),
                ('gamesWonRegular', models.FloatField()),
            ],
        ),
    ]
