# Generated by Django 5.0.6 on 2024-07-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GameHistory',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesTotal',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesWon',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesWonMulti',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gamesWonRegular',
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesWon', models.FloatField(default=0)),
                ('gamesTotal', models.FloatField(default=0)),
                ('gamesWonMulti', models.FloatField(default=0)),
                ('gamesWonRegular', models.FloatField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
