# Generated by Django 4.2.3 on 2024-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_division_user_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinium', 'Platinium'), ('diamond', 'Diamond'), ('master', 'Master'), ('challenger', 'Challenger')], default='bronze', max_length=11),
        ),
    ]
