# Generated by Django 4.2.3 on 2024-10-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match', to='matchmaker.match')),
                ('players', models.ManyToManyField(through='matchmaker.History', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.CharField(choices=[('local', 'Local'), ('online', 'En ligne')], default='local', max_length=20)),
                ('mode', models.CharField(choices=[('solo', 'Un joueur (VS IA)'), ('1v1', 'Multijoueur (1v1)'), ('2v2', 'Multijoueur (2v2)')], default='solo', max_length=20)),
                ('mm', models.CharField(choices=[('ranked', 'Classé'), ('unranked', 'Non Classé'), ('tournament', 'Tournoi')], default='unranked', max_length=20)),
            ],
            options={
                'unique_together': {('connect', 'mode', 'mm')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_info', to='matchmaker.matchchoice'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='match_team', to='matchmaker.team'),
        ),
        migrations.AddField(
            model_name='history',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_team', to='matchmaker.team'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
