# Generated by Django 4.2.3 on 2025-03-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import matchmaker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('marks_required', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='matchmaker.game')),
            ],
            options={
                'ordering': ['game', 'order'],
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matchmaker.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(choices=[('Local', 'Local'), ('En ligne', 'En ligne')], default='Local', max_length=20)),
                ('mode', models.CharField(choices=[('Solo', 'Un joueur (VS IA)'), ('1v1', 'Multijoueur (1v1)'), ('2v2', 'Multijoueur (2v2)')], default='Solo', max_length=20)),
                ('matchmaking', models.CharField(choices=[('Non Classé', 'Non Classé'), ('Classé', 'Classé'), ('Tournoi', 'Tournoi')], default='Non Classé', max_length=20)),
                ('game', models.ForeignKey(default=matchmaker.models.Game.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaker.game')),
            ],
            options={
                'unique_together': {('game', 'connectivity', 'mode', 'matchmaking')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaker.matchchoice'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='matchmaker.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='matchmaker.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(default=4)),
                ('marks', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to='matchmaker.game')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to='matchmaker.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
