# Generated by Django 5.0.6 on 2024-07-27 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('solo', 'Un joueur (VS IA)'), ('multi local', 'Multijoueur Local'), ('multi online', 'Multijoueur en ligne')], default='solo', max_length=20)),
                ('mm', models.CharField(choices=[('ranked', 'Ranked'), ('unranked', 'Unranked'), ('private', 'Private'), ('tournament', 'Tournament')], default='unranked', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_match', to='matchmaker.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_player', to='matchmaker.player')),
            ],
        ),
    ]
