# Generated by Django 4.2.3 on 2024-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='connect',
            field=models.CharField(choices=[('Local', 'Local'), ('Online', 'En ligne')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchchoice',
            name='mm',
            field=models.CharField(choices=[('Rank', 'Classé'), ('Unrank', 'Non Classé'), ('Tournament', 'Tournoi')], default='Unrank', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchchoice',
            name='mode',
            field=models.CharField(choices=[('Solo', 'Un joueur (VS IA)'), ('1v1', 'Multijoueur (1v1)'), ('2v2', 'Multijoueur (2v2)')], default='Solo', max_length=20),
        ),
    ]
