# Generated by Django 4.2.3 on 2025-03-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
