# Generated by Django 4.2.3 on 2025-02-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together={('game', 'connectivity', 'mode', 'matchmaking')},
        ),
        migrations.RemoveField(
            model_name='matchchoice',
            name='auto_fill',
        ),
    ]
