# Generated by Django 4.2.3 on 2025-03-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_player_is_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='romModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
