# Generated by Django 4.2.3 on 2024-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_alter_matchchoice_connect_alter_matchchoice_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='connect',
            field=models.CharField(choices=[('Local', 'Local'), ('En ligne', 'En ligne')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchchoice',
            name='mm',
            field=models.CharField(choices=[('Non Classé', 'Non Classé'), ('Classé', 'Classé'), ('Tournoi', 'Tournoi')], default='Non Classé', max_length=20),
        ),
    ]
