# Generated by Django 4.2.3 on 2024-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_alter_matchchoice_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='connect',
            field=models.CharField(choices=[('local', 'Local'), ('online', 'En ligne')], default='local', max_length=20),
        ),
    ]
