# Generated by Django 4.2.3 on 2025-03-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_rommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('rommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matchmaker.rommodel')),
            ],
            bases=('matchmaker.rommodel',),
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('rommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matchmaker.rommodel')),
            ],
            bases=('matchmaker.rommodel',),
        ),
        migrations.CreateModel(
            name='LobbyRequest',
            fields=[
                ('rommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matchmaker.rommodel')),
            ],
            bases=('matchmaker.rommodel',),
        ),
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('rommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matchmaker.rommodel')),
            ],
            bases=('matchmaker.rommodel',),
        ),
        migrations.CreateModel(
            name='WaitingLobby',
            fields=[
                ('rommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matchmaker.rommodel')),
            ],
            bases=('matchmaker.rommodel',),
        ),
    ]
