# Generated by Django 4.2.3 on 2025-03-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_lobby_lobbyplayer_lobbyrequest_matchmaking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='rommodel_ptr',
        ),
        migrations.RemoveField(
            model_name='lobbyrequest',
            name='rommodel_ptr',
        ),
        migrations.RemoveField(
            model_name='matchmaking',
            name='rommodel_ptr',
        ),
        migrations.RemoveField(
            model_name='waitinglobby',
            name='rommodel_ptr',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='LobbyPlayer',
        ),
        migrations.DeleteModel(
            name='LobbyRequest',
        ),
        migrations.DeleteModel(
            name='Matchmaking',
        ),
        migrations.DeleteModel(
            name='romModel',
        ),
        migrations.DeleteModel(
            name='WaitingLobby',
        ),
    ]
