# Generated by Django 4.2.3 on 2024-12-05 00:06

from django.db import migrations, models
import django.db.models.deletion
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_team_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_info', to='matchmaker.matchchoice'),
        ),
    ]
