# Generated by Django 4.2.3 on 2024-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_match_players_alter_history_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
