# Generated by Django 4.2.3 on 2025-03-31 14:02

from django.db import migrations, models
import django.db.models.deletion
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_remove_lobbyplayer_rommodel_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='marks_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(default='unranked', max_length=20),
        ),
        migrations.AlterField(
            model_name='rank',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(default=matchmaker.models.Rank.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to='matchmaker.rank'),
        ),
    ]
