# Generated by Django 4.2.3 on 2024-12-05 00:09

from django.db import migrations, models
import django.db.models.deletion
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_alter_match_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.ForeignKey(default=matchmaker.models.get_default_match_choice_id, on_delete=django.db.models.deletion.CASCADE, related_name='match_info', to='matchmaker.matchchoice'),
        ),
    ]
