# Generated by Django 4.2.3 on 2024-12-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0006_alter_match_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchchoice',
            old_name='connect',
            new_name='connectivity',
        ),
        migrations.RenameField(
            model_name='matchchoice',
            old_name='mm',
            new_name='matchmaking',
        ),
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together={('connectivity', 'mode', 'matchmaking')},
        ),
    ]
