# Generated by Django 4.2.3 on 2025-01-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaker', '0007_rename_connect_matchchoice_connectivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.ForeignKey(default=matchmaker.models.get_default_match_choice_id, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaker.matchchoice'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='matchmaker.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='matchmaker.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='matchmaker.Entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='History',
        )
    ]
