# Generated by Django 4.2.3 on 2025-02-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0009_game_rank_userrank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchchoice',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaker.game'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together={('game', 'connectivity', 'mode', 'matchmaking')},
        ),
    ]
