# Generated by Django 4.2.3 on 2025-02-04 17:29

from django.db import migrations, models
import django.db.models.deletion
import matchmaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0011_alter_matchchoice_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='game',
            field=models.ForeignKey(default=matchmaker.models.Game.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaker.game'),
        ),
    ]
