# Generated by Django 4.2.3 on 2025-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0012_alter_matchchoice_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchchoice',
            name='auto_fill',
            field=models.BooleanField(default=True),
        ),
    ]
