# Generated by Django 4.2.3 on 2025-02-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0013_matchchoice_auto_fill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchchoice',
            unique_together={('game', 'connectivity', 'mode', 'matchmaking', 'auto_fill')},
        ),
    ]
