# Generated by Django 4.2.3 on 2025-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0014_alter_matchchoice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchchoice',
            name='auto_fill',
            field=models.BooleanField(default=False),
        ),
    ]
