# Generated by Django 4.2.3 on 2024-10-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'En Ligne'), ('offline', 'Hors Ligne'), ('in game', 'En Jeu'), ('invisible', 'Invisible'), ('busy', 'Occupé')], default='offline', max_length=9),
        ),
    ]
