# Generated by Django 4.2.3 on 2024-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='static/account/media/default_banner.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/account/media/default_avatar.png', upload_to=''),
        ),
    ]
