# Generated by Django 4.2.3 on 2024-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_banner_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'En Ligne'), ('offline', 'Hors Ligne'), ('in game', 'En Jeu'), ('invisible', 'Invisible'), ('busy', 'Occupé')], default='online', max_length=9),
        ),
    ]
