# Generated by Django 4.2.3 on 2024-11-09 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
