# Generated by Django 4.2.3 on 2024-11-10 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_friends_alter_user_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En jeu', 'En Jeu'), ('Invisible', 'Invisible'), ('Occupé', 'Occupé')], default='Actif', max_length=9),
        ),
    ]
