# Generated by Django 4.2.3 on 2024-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_requests_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En jeu', 'En Jeu'), ('Invisible', 'Invisible'), ('Occupé', 'Occupé')], default='Inactif', max_length=9),
        ),
    ]
