# Generated by Django 4.2.3 on 2024-11-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
