# Generated by Django 4.2.3 on 2024-11-22 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_session_ip_address_alter_session_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
