# Generated by Django 4.2.3 on 2024-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_session_ip_address_alter_session_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('En Ligne', 'En Ligne'), ('Hors Ligne', 'Hors Ligne'), ('Dans une partie', 'Dans une partie'), ('Invisible', 'Invisible'), ('Occupé', 'Occupé'), ('Dans un salon', 'Dans un salon')], default='Hors Ligne', max_length=15),
        ),
    ]
